### ISSUE TITLE
Problem with candle

### ISSUE THREAD

**Issue by drmillan** [felfert/docker-wix#2]
I am using this docker image for a little project, but at this moment candle comand is throwing :
----
Windows Installer XML Toolset Compiler version 3.11.2.4516
Copyright (c) .NET Foundation and contributors. All rights reserved.

build.wxs
candle.exe : error CNDL0050 : Access to the path 'build.wixobj' is denied.
----

This build was working on an old docker image version (since it is not tagged, it just downloaded latest version on a new computer and the build does not work)

**Comment by felfert** [comment]
The last change was [this](https://github.com/felfert/docker-wix/commit/d638831320b09e2af19ad8bc48083855adcbbd32)
 - Did you regenerate your host wrappers?
 - Are you using docker or podman?
 - On what host distro?
 - If selinux is enabled, does it work after running setenforce 0 ?

**Comment by drmillan** [comment]
1.- host wrappers are always regenerated in every build
2.- docker
3.- ubuntu 18
4.- have to check, I had to change the scripts for building in a "real" vmware windows as emergency solution

**Comment by felfert** [comment]
Ok, since you are running docker on ubuntu 18 (it does not use selinux), then you probably can change the generated candle script to use an empty SECOPTS. If this still does not help, then it is most likely a regular permission problem, so make shure your output directory is writeable by the docker container.

**Comment by felfert** [comment]
Ok, in the meantime, I tested it myself on a fresh Ubuntu 18.04 LTS host with a minimal example.wxs. It worked fine.
=> So this is definitively an ordinary permission problem.

**Comment by felfert** [comment]
This worked fine here, using [this example](https://pastebin.com/Faeg3exY)
```
mkdir x
cd x
[Save text from pastebin as example.wxs]
docker run --rm felfert/wix mkhostwrappers | sh
./candle example.wxs
./light -sval example.wixobj
```

**Comment by felfert** [comment]
Closed - no more responses from issuer - not a bug
